### PR TITLE
Remove AppendBlkAllocMetrics

### PR DESCRIPTION
**Pull request by yuwmao**

### CODE REVIEW

**Comment by JacksonYao287** [comment]
1  should we also remove this?
https://github.com/eBay/HomeStore/pull/457/files#diff-13da7c9cb39c3438e8d74a85f9fa420418cbe29ff407fe45177a25f03e8f3bf5R43

2 does this PR has any relationship with this issue
[#176](https://github.com/eBay/HomeObject/issues/176)

**Comment by yuwmao** [comment]
> 1 should we also remove this? https://github.com/eBay/HomeStore/pull/457/files#diff-13da7c9cb39c3438e8d74a85f9fa420418cbe29ff407fe45177a25f03e8f3bf5R43
> 
> 2 does this PR has any relationship with this issue [#176](https://github.com/eBay/HomeObject/issues/176)

For 1, not sure whether histogram metrics will reuse this structure, let's comment out it at the moment.
For 2, I think #176 can be closed.

**Comment by JacksonYao287** [comment]
ok , i will close https://github.com/eBay/HomeObject/issues/176
please update homestore version in conanfile `6.4.22 -> 6.4.23`, other parts looks good to me.

**Comment by yuwmao** [comment]
> ok , i will close [eBay/HomeObject#176](https://github.com/eBay/HomeObject/issues/176) please update homestore version in conanfile `6.4.22 -> 6.4.23`, other parts looks good to me.

Sure, updated.

**Review by JacksonYao287 — APPROVED** [review]
LGTM!

**Pull request merged**
