### PR TITLE
inject flip into io path to simulate io error and stuck io

### PR DESCRIPTION
**Pull request by JacksonYao287**
this PR inject flip point to simulate io_error and stuck io in read/write path , which will be used for later long running test
#401

### CODE REVIEW

**Review by xiaoxichen — COMMENTED** [review]
can we move the 
```
    if (iomgr_flip::instance()->test_flip("blk_write_failure")) {
        return folly::makeFuture< std::error_code >(std::make_error_code(std::errc::io_error));
    }
    if (iomgr_flip::instance()->test_flip("blk_write_stuck")) {
        std::this_thread::sleep_for(std::chrono::hours(24 * 365 * 100)); // Sleep for 100 years
        return folly::makeFuture< std::error_code >(std::make_error_code(std::errc::resource_unavailable_try_again));
    }
```
into  a function ?

**Comment by JacksonYao287** [comment]
> can we move the
> 
> ```
>     if (iomgr_flip::instance()->test_flip("blk_write_failure")) {
>         return folly::makeFuture< std::error_code >(std::make_error_code(std::errc::io_error));
>     }
>     if (iomgr_flip::instance()->test_flip("blk_write_stuck")) {
>         std::this_thread::sleep_for(std::chrono::hours(24 * 365 * 100)); // Sleep for 100 years
>         return folly::makeFuture< std::error_code >(std::make_error_code(std::errc::resource_unavailable_try_again));
>     }
> ```
> 
> into a function ?

will wrap them into a macro

**Review by xiaoxichen — COMMENTED** [review]
my personal taste prefer inline compared to macro, but sort of preference's territory. 

LGTM

**Comment by JacksonYao287** [comment]
> my personal taste prefer inline compared to macro, but sort of preference's territory.
> 
> LGTM

i think it does not matter to use macro or inline for the case here, since it will not bring too much impact. so can you give an approval?

**Review by xiaoxichen — APPROVED** [review]

**Pull request merged**
