### PR TITLE
fix restartability bug for upper layer

### PR DESCRIPTION
**Pull request by JacksonYao287**
if it is not first-time-boot, the uuid of HO is saved in metaservice. so we need to get the uuid after metaservice is started, otherwise we will get a new default uuid

### CODE REVIEW

**Comment by xiaoxichen** [comment]
This suggests we are wrong in https://github.com/eBay/HomeStore/pull/284/files
for restart,  the `_our_id` in HO is set by `homestore_metablk_callback`,  which will be called after meta svc started in https://github.com/eBay/HomeStore/blob/master/src/lib/homestore.cpp#L210

In the #284 we move the initialization of  GenericReplService from `start` to `do_start`.

I think we either
a.  move https://github.com/eBay/HomeStore/blob/master/src/lib/homestore.cpp#L198 down below L210
or 
b. move L198 back to start() , remove wrong comments and  take the change in this PR to get uuid in GenericReplService::start() in L217

**Review by xiaoxichen — DISMISSED** [review]
check back with #284

**Comment by JacksonYao287** [comment]
@xiaoxichen 
for a, we can not make this change,  since the `register_handler` happens in the constructor of `RaftReplService`
https://github.com/eBay/HomeStore/blob/67cca17a715f08975ab7f28f211cdfe34963fbeb/src/lib/replication/service/raft_repl_service.cpp#L64
if we put L198 down below L210, then the handler can not be registered before metaservice#start, which will lead to a missing raft config.

well, b is acceptable, will do this!

**Review by xiaoxichen — APPROVED** [review]
lgtm

Though we had seen an initialized uuid default value for `m_repl_app->get_my_repl_id()` and do not know the reason, but maybe 
`        RELEASE_ASSERT(!m_my_uuid.value().is_nil(), "Uninitialized RaftReplService UUID");`

**Comment by JacksonYao287** [comment]
> lgtm
> 
> Though we had seen an initialized uuid default value for `m_repl_app->get_my_repl_id()` and do not know the reason, but maybe ` RELEASE_ASSERT(!m_my_uuid.value().is_nil(), "Uninitialized RaftReplService UUID");`

ok, will add it in the later coming PR

**Pull request merged**
